projects:
  unibedocs:
    schemaPath: amplify/backend/api/unibedocs/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
      - ''
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
