name: Deploy

on:
  push:
    branches:
      - main
      - unibe/main
  pull_request:
    branches:
      - main
      - unibe/main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.4'

      - name: Create aws-exports.js
        run: |
          echo "const awsmobile = $(echo '${{ secrets.UNIBE_EXPORTS_AWS }}' | jq '.');" > ./src/aws-exports.js
          echo "export default awsmobile;" >> ./src/aws-exports.js
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy
        run: |
          echo "Deploying..."
