name: Deploy

on:
  push:
    branches:
      - main
      - unibe/main
  pull_request:
    branches:
      - main
      - unibe/main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.4'

      - name: Install dependencies
        run: npm install

      - name: Configurar aws-exports.js
        run: |
          echo "${{ secrets.AWS_EXPORTS }}" > ./src/aws-exports.js

      - name: Verificar contenido de aws-exports.js
        run: |
          echo "Contenido de aws-exports.js:"
          cat ./src/aws-exports.js

      - name: Build the project
        run: npm run build

      - name: Deploy
        run: |
          echo "Deploying..."
